name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore NuGet packages
        run: nuget restore IntuneAppRepairTool.sln

      - name: Build with MSBuild
        run: |
          & "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe" `
            IntuneAppRepairTool.sln `
            /p:Configuration=Release `
            /p:Platform="Any CPU"
        shell: pwsh

      - name: Zip output
        run: |
          $tag = "${{ github.ref_name }}"
          $zipName = "IntuneAppRepairTool_$tag.zip"
          Compress-Archive -Path bin\Release\* -DestinationPath $zipName
          echo "ZIP_NAME=$zipName" >> $env:GITHUB_ENV
        shell: pwsh

      - name: Create GitHub Release and Upload Artifact
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: ${{ env.ZIP_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
